java_library(
    name = "time",
    testonly = 1,
    srcs = glob(["**/*.java"]),
    javacopts = ["-XepDisableAllChecks"],
    deps = [
        "//src/main/java/org/joda/time",
        "//third_party/junit",
        "//third_party/org/joda:joda_convert",
    ],
)
